/**
* Swagger Petstore
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.server.models


/**
 * 
 * @param name 
 * @param email 
 * @param tel 
 */
data class InlineResponse200 (
    val name: kotlin.String? = null,
    val email: kotlin.String? = null,
    val tel: kotlin.String? = null
) 

