openapi: 3.0.0
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: 'http://petstore.swagger.io/v1'
paths:
  '/pets/{petId}':
    get:
      summary: Info for a specific pet
      operationId: showPetById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: The id of the pet to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                title: Pet
                description: A single pet.
                type: object
                x-tags:
                  - Pets
                properties:
                  name:
                    type: string
                    example: doggie
                  photoUrls:
                    type: array
                    items:
                      type: string
                  status:
                    type: string
                    description: pet status in the store
                    enum:
                      - available
                      - pending
                      - sold
                required:
                  - name
                  - photoUrls
        '404':
          description: Not Found
  '/persons/{personId}':
    get:
      summary: 飼い主の情報
      tags:
        - pets
      responses:
        '200':
          description: Get Person Information
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  email:
                    type: string
                  tel:
                    type: string
      operationId: showPersonById
    parameters:
      - schema:
          type: string
        name: personId
        in: path
        required: true
