/**
* Swagger Petstore
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.server.apisimpl


import com.google.gson.Gson
import io.ktor.application.call
import io.ktor.http.ContentType
import io.ktor.locations.KtorExperimentalLocationsAPI
import io.ktor.locations.get
import io.ktor.response.respond
import io.ktor.response.respondText
import io.ktor.routing.Route
import org.openapitools.server.Paths

@KtorExperimentalLocationsAPI
fun Route.PetsApi() {
    val gson = Gson()
    val empty = mutableMapOf<String, Any?>()

    get { _: Paths.showPersonById ->
        // val exampleContentType = "application/json"
        val exampleContentString = """{
          "name" : "name",
          "tel" : "tel",
          "email" : "email"
        }"""
        
        call.respond(gson.fromJson(exampleContentString, empty::class.java))
    }


    get { _: Paths.showPetById ->
        // val exampleContentType = "application/json"
        val exampleContentString = """{
          "photoUrls" : [ "photoUrls", "photoUrls" ],
          "name" : "doggie"
        }"""
        
        call.respond(gson.fromJson(exampleContentString, empty::class.java))
    }

}
